#!/bin/bash
# init shell script

# delete previous outfile to more easily find errors
rm -f outfile

# pipe grep into growing file
tail -f /var/log/pihole.log | fgrep --line-buffered gravity.list >> outfile &

# init node stuff

# node server.js or something
